# Ненормативная лексика!
banned_words = {
    # Маты основные
    "хуй", "хуя", "хуё", "хуем", "хуе", "хуи", "хуёв", "хуям", "хуями", "хуйло", "хуйня",
    "хуев", "хует", "хуёвый", "хуёвая", "хуёвое", "хуёвые", "хуёвым", "хуёвыми", "нахуй"
                                                                                 "пизда", "пизды", "пизде", "пизду",
    "черт","чорт","чертила","хуесос","мымра","говноед","ебливая",
    "ебливый","дрючело","цыгит","факин","факну","ракну"
    "пиздой", "пиздо", "пизд", "пиздец", "пиздюк",
    "пиздюки", "пиздюли", "пиздабол", "пиздатая", "пиздатое", "пиздатые",

    # Пидорас и варианты
    "пидорас", "пидораска", "пидорасы", "пидарас", "пидараска", "пидарасы",
    "педорас", "педерас", "педрила", "пидор", "пидоры", "пидорок",

    # Ебать и производные
    "ебал", "ебала", "ебали", "ебать", "ебу", "ебешь", "ебёт", "еби", "ебаш", "ебашит",
    "ебашим", "ебашите", "ебан", "ебана", "ебаное", "ебаной", "ёбаный", "ёбаная", "ёбаное",
    "ёбаные", "заеб", "заеба", "заебали", "уеб", "уеба", "уебали", "проеб", "проеба",
    "проебали", "долбаёб", "долбоёб", "долбаёбы", "долбоёбы", "объеб", "объеба",

    # Блядь и варианты
    "блядь", "бляди", "блядью", "блядям", "блядями", "бля", "блять", "бляд", "блядун",
    "блядины", "блядство", "блядский", "блядская", "блядское", "блядские", "блядовать",

    # Нах и производные
    "нах", "похуй", "похую", "нахер", "нахрен", "нахуй", "нахуя", "нихуя", "нихуёво",

    # Оскорбления дополнительные
    "чмо", "чмырь", "чмарить", "гандон", "гандоны", "гондон", "гондоны", "мудак", "мудаки",
    "мудила", "мудилы", "мразь", "мрази", "мразота", "отстой", "никчема", "выблядок", "ублюдок",
    "дебил", "дебила", "дебилу", "дебилом", "дебилы", "дебилов", "дибил", "дибила", "дэбил", "дэбила",
    "даун", "дауна", "дауны", "идиот", "идиота", "идиоту", "идиотом", "идиоты", "идиотка", "идиотки",
    "тупица", "тупицы", "тупой", "тупого", "тупому", "тупые", "тупых", "придурок", "придурка",
    "придурки", "придурков", "кретин", "кретина", "кретины", "урод", "урода", "уроду", "уроды",
    "уродина", "уродины", "скотина", "скотины", "скотину", "сволочь", "сволочи", "подонок",
    "подонка", "подонки", "гадина", "гадины", "тварь", "твари", "сука", "суки", "суку",
    "сучка", "сучки", "шавка", "шавки", "шлюха", "шлюхи", "шлюху", "проститутка", "проститутки",
    "проститутку", "шалава", "шалавы", "блудница", "блудницы", "гнида", "гниды", "падла", "падлы",
    "сосите", "сосать", "выблядки", "долбаебы", "долбаёбы", "долбаеб", "чувырла", "чувырлы", "сосо",
    "уебок", "уебки", "уебище", "уебища", "какашка", "какашки",
    "xyй", "xyя", "xyё", "хyй", "хyя","лох","лошара",
    "пизд@", "пізда", "пиздец",
    "єбал", "єбать", "єбнутый",
    "блять", "бляд", "бліадь",
    "сцука", "с@ка", "сук@",
    "муд@к", "пид@р", "долбаёб",
    "заєбал", "похую", "нахуй",

    # Сексуальные и физиологические
    "выебок", "выебываться", "дрочить", "дрочка", "конча", "сперма", "секс", "трах", "выеб",
    "выебать", "отсос", "минет", "пезда", "манда", "срака", "срать", "говно", "гавно", "дерьмо",
    "залупа", "хер", "хрен", "член", "писька", "вагина", "анальный", "мастурбация", "отсосите",
    "дырявый", "дырявые",

    # Угрозы и агрессия
    "убью", "убить", "зарежу", "зарублю", "сдохни", "подохни", "помри", "сдохнуть",

    # Запрещенный контент
    "порно", "порнография", "эротика", "секс",
    # Английские маты
    "fuck", "fucker", "fucking", "motherfucker", "fuckoff",
    "shit", "bullshit", "shitty", "shitter",
    "ass", "asshole", "dumbass", "badass", "asshat",
    "bitch", "bitches", "bitching", "sonofabitch",
    "dick", "dickhead", "dickface", "dicksucker",
    "pussy", "pussies", "pussyhole",
    "cunt", "cunts", "cuntface",
    "whore", "whores", "whorehouse",
    "bastard", "bastards",
    "slut", "sluts", "slutty",
    "nigger", "nigga", "niggers",
    "retard", "retarded", "retards",
    "fag", "faggot", "fags", "faggots",
    "douche", "douchebag", "douchebags",
    "cock", "cocks", "cocksucker",
    "wanker", "wankers", "wanking",
    "twat", "twats",
    "bollocks", "bollox",
    "arse", "arsehole", "arses",
    "prick", "pricks", "prickhead", "stupid",

    # Транслит матов
    "hui", "huy", "xyi", "xuy", "xyu", "xui", "hyi", "hyu",
    "pizda", "pizdec", "pizdets", "pizdobol", "pizdoprop", "pizduy",
    "ebat", "ebal", "ebala", "ebali", "ebanutiy", "ebaniy", "eban", "eblan", "ebola",
    "blyad", "bliad", "blyat", "bliat", "blat", "bljad", "blat", "blya", "blia",
    "suka", "cyka", "suki", "cyki", "suchka", "suczka", "sykа",
    "govno", "gavno", "govnish", "gavnish",
    "mudak", "mudaki", "mudila", "mudilo",
    "pidor", "pider", "pedik", "pedril", "pedir", "pidaras", "pedor",
    "jopa", "zhopa", "jopi", "zhopi", "jopu", "zhopu",
    "zalupa", "zalupi", "zalup",
    "chlen", "4len", "chlena", "chlenos",
    "spirma", "sperma", "spirmu",
    "shlucha", "shluha", "shljoha", "shluhi",
    "prostitutka", "prostitura", "prosti",
    "debil", "dybil", "debiloid",
    "daun", "dawn", "daunoid",
    "idiot", "ydiot", "idiotoid",
    "kretin", "cretin", "kretinoid",
    "pridurok", "pridyrok", "pridur",
    "ueban", "yeban", "uebische",
    "zaebis", "zaebys", "zaeb",
    "dolbaeb", "dolbayob", "dolboeb",
    "otebis", "otyebis", "oteb",
    "sebi", "syebi", "seb",
    "drochit", "dro4it", "droch",
    "koncha", "kon4a", "konch",
    "masturbacia", "mastyrbacia",
    "viblyadok", "vibladok",
    "ubludok", "yubludok",
    "chert", "cherti", "chort",
    "chertovo", "chortovo",
    "adski", "adskiy",
    "paskuda", "paskudny",
    "merzavets", "merzaviy",
    "gadina", "gadiny",
    "tvarina", "tvar",
    "stupid",
    "idi0t", "idiot", "id10t", "id1ot",
  # Угрозы взломом и оскорбления (отдельные слова)
    "взломан", "взломаю", "хакну", "слит",
    "лох", "дурак", "чертилы", "чертила", "чертяра", "дьяволята",
    "лузеры", "лохи", "разраб", "идиот", "дебил", "пидор", "мудак",
    "слив", "украду", "говно", "гавно", "дерьмо"
}

banned_phrases = {
    # Секс и интим
    "секс знакомства", "интим встречи", "знакомства для секса", "взрослые встречи",
    "интим досуг", "взрослый досуг", "секс услуги", "интим услуги",

    # Матерные фразы
    "пошёл нахуй", "пошла нахуй", "пошли нахуй", "иди нахуй", "идите нахуй",
    "иди нахер", "идите нахер", "иди в пизду", "пошёл на хер", "пошла на хер",
    "пошли на хер", "заткнись", "заткнитесь", "отъебись", "отъебитесь",
    "пошёл ты", "пошла ты", "пошли вы", "иди ты", "идите вы", "отвали",
    "отвалите", "завали ебало", "завалите ебало", "завали хлебало",
    "пошёл в пизду", "пошла в пизду", "пошли в пизду", "иди в жопу",
    "пошёл в жопу", "пошла в жопу", "иди к чёрту", "пошёл к чёрту",
    "пошла к чёрту", "чёрт побери", "блядь ёб", "ёб твою мать", "ёб вашу мать",
    "ёб твою", "ёб вашу", "ахуеть можно", "охуеть можно", "на хуй нужно",
    "на хер нужно", "на хуй надо", "на хер надо", "пиздец какой", "пиздец как",
    "охуенный результат", "ахуенный результат", "охуеть какой", "ахуеть какой",

    # Угрозы и агрессия
    "убью тебя", "зарежу тебя", "сдохни тварь", "подохни сука", "сдохни урод",
    "подохни тварь", "убью вас", "зарежу вас", "го в доту", "играть в доту",
    "играть в кс", "го в кс", "го в контру", "играть в контру",

    # Оскорбительные фразы
    "ты дебил", "вы дебилы", "ты идиот", "вы идиоты", "тупой урод",
    "тупая скотина", "глупая тварь", "никчёмный человек", "ты дурак",
    "вы дураки", "ты придурок", "вы придурки", "ты кретин", "вы кретины",
    "ты мразь", "вы мразь", "ты подонок", "вы подонки", "ты пидорас",
    "вы пидорасы", "ты чмо", "вы чмо", "ты мудак", "вы мудаки",

    # Дополнительные матерные фразы
    "иди отсюда", "пошёл отсюда", "пошла отсюда", "валить отсюда",
    "катись отсюда", "проваливай", "проваливайте", "съебись", "съебитесь",
    "отъебись отсюда", "отъебитесь отсюда", "заебал уже", "заебали уже",
    "достал уже", "достали уже", "надоел уже", "надоели уже", "это слив", "слив бота",
    "отсосите выблядки", "я вашы рты ебал",
    "изи слив",
    # Английские маты
    "fuck you", "fuck u", "fuck off", "fuck yourself",
    "shit you", "shit u", "shit off", "shit yourself",
    "suck my dick", "suck my cock", "suck it", "suck this",
    "bite me", "bite my ass",
    "go to hell", "burn in hell", "go hell",
    "kill yourself", "kill you", "kill u",
    "die bitch", "die asshole", "die motherfucker",
    "screw you", "screw u", "screw off",
    "piss off", "piss you", "piss u",
    "damn you", "damn u", "goddamn you",
    "mother fucker", "son of a bitch",
    "what the fuck", "what the hell", "what the shit",
    "who the fuck", "who the hell",
    "fucking hell", "fucking shit", "fucking ass",
    "stupid ass", "stupid fuck", "stupid bitch",
    "dumb ass", "dumb fuck", "dumb bitch",
    "you suck", "u suck", "you bitch", "u bitch",
    "you asshole", "u asshole", "you bastard", "u bastard",
    "you whore", "u whore", "you slut", "u slut",
    "you fag", "u fag", "you faggot", "u faggot",
    "you nigger", "u nigger", "you nigga", "u nigga",
    "you retard", "u retard", "you moron", "u moron",
    "you idiot", "u idiot", "you stupid", "u stupid",
    "st up id", "st.up.id",

    # Транслит фраз
    "idi na hui", "idi na huy", "idi na xyi", "idi na xuy",
    "idi nahu", "idina xuy", "idina xyi", "idina huy",
    "poshel na hui", "pohel na huy", "poshel na xuy", "pohel na xyi",
    "idi ti", "poshel ti", "pohel ti", "shol ti",
    "zaebal", "doebal", "zdoebal", "pereeebal",
    "ebat ti rot", "ebal ti rot", "ebti rot", "eb tvoi rot",
    "hui sosi", "huy sosi", "xyi sosi", "xuy sosi",
    "sosi hui", "sosi xuy", "sosat huy", "sosat xyi",
    "suka blyat", "cyka blyat", "suka bliat", "cyka bliat",
    "suka nahuy", "cyka nahuy", "suka naxuy", "cyka naxuy",
    "ti debil", "ti idiot", "ti durak", "ti dura",
    "ti pidor", "ti pedik", "ti mudak", "ti urod",
    "otvali", "otvali ot menya", "otvali otsuda",
    "pashol von", "poshel von", "pohel von",
    "mne pohui", "mne pohuy", "mne po xyi", "mne po xuy",
    "mne pofig", "mne pofyg", "mne poher",
    "k chertu", "k chertam", "k chortu",
    "yeb ti", "eb ti", "yeb tebya", "eb tebya",
    "proebal", "proeb", "proebat", "proyeb",
    "razebis", "razeb", "razebat",
    "uebivay", "yebivay", "uebivai",
    "otebis otsuda", "syebis otsuda",
    "zaebis kak", "zaebis kruto",
    "doebalis", "doebali", "zdoebali",
    "na hui nujen", "na huy nujen", "na xyi nujen",
    "naher nujen", "naher nada", "nahren nada",
    "v pizdu", "v pizdu ot", "v pizdec",
    "v jopu", "v zhopu", "v jopu ti",
    "v rot ebal", "v rot eb", "v rylo ebal",
    "ti mne nadоеl", "ti mne nadoyel",
    # Угрозы взломом и оскорбления (фразы)
    "бот взломан", "система изи", "основатель лох",
    "взломаю бота", "взломаю тг", "хакну бота", "слит бот",
    "основатель дурак", "создатель лох", "разработчик лох",
    "админы лузеры", "админы лохи", "разраб дурак",
    "слив базы", "слив данных", "украду базу",
    "взломаю систему", "взломаю вас", "хакну вас",
    "бот говно", "бот гавно", "бот дерьмо",
    "создатель идиот", "разработчик дебил",
    "админ пидор", "владелец мудак"
}

